# The paging call adapter rewrites the @PagingKey argument on a cloned Retrofit call.
# OkHttpCall is package private, so the field is located by type rather than by name, but
# it still has to survive shrinking.
-keepclassmembers class retrofit2.OkHttpCall {
    private java.lang.Object[] args;
}

# Mapper classes are only referenced as a KClass value inside @PagingKeyConfig, which R8 does
# not treat as a keep root. Without this they are shrunk away and cannot be instantiated.
-keep class * implements com.skydoves.retrofit.adapters.paging.PagingMapper {
    <init>();
}

# The registry generated by retrofit-adapters-paging-compiler is looked up by name.
-keep class com.skydoves.retrofit.adapters.paging.generated.GeneratedPagingMapperRegistry {
    <init>();
}
