/*
 * Copyright (C) 2022 skydoves (Jaewoong Eum)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.skydoves.retrofit.adapters.paging.internals

import com.skydoves.retrofit.adapters.paging.PagingMapper
import com.skydoves.retrofit.adapters.paging.PagingMapperRegistry

/**
 * @author skydoves (Jaewoong Eum)
 * @since 1.2.0
 *
 * Instantiates [PagingMapper]s, preferring the registry generated by the
 * `retrofit-adapters-paging-compiler` KSP processor and falling back to reflection when the
 * processor is not applied.
 */
internal object PagingMappers {

  private const val GENERATED_REGISTRY =
    "com.skydoves.retrofit.adapters.paging.generated.GeneratedPagingMapperRegistry"

  private val generatedRegistry: PagingMapperRegistry? by lazy(LazyThreadSafetyMode.PUBLICATION) {
    runCatching {
      Class.forName(GENERATED_REGISTRY).getDeclaredConstructor().newInstance()
    }.getOrNull() as? PagingMapperRegistry
  }

  fun create(mapperClass: Class<*>): PagingMapper<*, *> {
    generatedRegistry?.create(mapperClass)?.let { return it }

    val instance = try {
      mapperClass.getDeclaredConstructor().newInstance()
    } catch (e: ReflectiveOperationException) {
      throw IllegalArgumentException(
        "The mapper class ${mapperClass.name} could not be instantiated. It must be a class with " +
          "a no-argument constructor, and it must be kept by R8. Apply the " +
          "retrofit-adapters-paging-compiler KSP processor, or keep the class explicitly.",
        e,
      )
    }

    return instance as? PagingMapper<*, *> ?: throw IllegalArgumentException(
      "The mapper parameter class must implement the PagingMapper interface: ${mapperClass.name}",
    )
  }
}
